### ISSUE TITLE
Error compiling library

### ISSUE THREAD

**Issue by AcuarioCat** [lorol/LITTLEFS#14]
Hi,
when I compile the library I'm getting an error (I'm just trying one of the examples):
I'm using the latest version from Github.

`esp_littlefs.c: In function esp_vfs_littlefs_register
 
esp_littlefs.c: 203:9: error: unknown field 'utime_p' specified in initializer
   utime_p     = &vfs_littlefs_utime`

**Comment by lorol** [comment]
Hi
Uncomment the line
 #define CONFIG_LITTLEFS_FOR_IDF_3_2 
in esp_littlefs.c.

**Comment by w00000dy** [comment]
What does "_old IDF_" mean? 
What do I have to do that I don't have to uncomment this line?

**Comment by lorol** [comment]
Are you using platformio?

**Comment by w00000dy** [comment]
yes

**Comment by lorol** [comment]
Use the previous release of the library and see the platformio example.

**Comment by solroshan** [comment]
Hello geezers,
I got an error looks like yours, here it is;

![build](https://user-images.githubusercontent.com/75987087/103011347-ce8a5200-454a-11eb-8c1f-9d4916692335.jpeg)
Here my .ini details;
![env details](https://user-images.githubusercontent.com/75987087/103010977-3a1fef80-454a-11eb-9993-e683b2f03f21.jpeg)

Checked the "esp_littlefs.c" for uncomment  the line
#define CONFIG_LITTLEFS_FOR_IDF_3_2
But this line already defined.
Also i changed the library with previous release(1.0.4)
Error is constant for now :(

I'll come back here If I find a way to fix. Ciao..

**Comment by solroshan** [comment]
> Hi
> Uncomment the line
> #define CONFIG_LITTLEFS_FOR_IDF_3_2
> in esp_littlefs.c.

Yuppie! Its worked. I checked 2nd time the #define idf3.2 line and error gone away permanently.
Thank you @lorol

**Comment by ndastur** [comment]
I think it better to define this in ```platformio.ini```

```
build_flags =
    -DCONFIG_LITTLEFS_FOR_IDF_3_2
```
