### ISSUE TITLE
LFS_NAME spiffs override for Arduino library

### ISSUE THREAD

**Issue by tsctrl** [lorol/LITTLEFS#17]
Hi @lorol,

`static constexpr const char LFS_NAME[] = "spiffs";`

wondering why the partition name was defaulted/const to spiffs and how to override or add more values in the sketch?
i think this could be any value that user set in the partition table.

Thank you

**Comment by lorol** [comment]
The main reason was to re-use uploading tool and existing partition schemes, w/o adding new ones.
See here: https://github.com/lorol/arduino-esp32fs-plugin/blob/master/src/ESP32FS.java#L274
If you you are using your own string, then the uploading add-on for Arduino IDE will not work.

In fact, as I mention, even the "type" / "sub-type" constants are also re-used. Using a new value, dedicated for LittleFS on ESP32 platforms should be "blessed" by Espressif. I just kept simple and re-usable.

In 2 words the LittleFS is not yet documented/defined/standardized.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html#subtype
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/spi_flash.html#_CPPv433ESP_PARTITION_SUBTYPE_DATA_SPIFFS

BTW, what is the deal to have different name in partition scheme?

**Comment by tsctrl** [comment]
Hi @lorol,

understood, the partition label/name itself can be define with custom value. this is to have better control when selecting/loading different partition to read.

ESP-IDF Partition Table
Name,   Type, SubType, Offset,  Size, Flags
anyvalue1,  data, spiffs,     0x4000,  1M,
anyvalue2,  data, spiffs,     0x8000,  1M,

refer to the existing SPIFFS library implementation here: [libraries/SPIFFS/src/SPIFFS.h#L27](https://github.com/espressif/arduino-esp32/blob/2452c1fb539246e47a715b74a3ad25b8a7ebbec7/libraries/SPIFFS/src/SPIFFS.h#L27)

the SPIFFS library allow us to select different partition label to load by specifying partitionLabel parameter. if this existing SPIFFS library works on the upload tools than probably the partition label was actually set somewhere during the library load. however for littleFS the label was set as constant in the library itself so that limit the possibility for us to use different partition label. I believe that the upload library should be able to read all available partition to write instead of using predefined values.

to note here, the partition label is any value that can be set and not always 'spiffs'. but not the type and subtype. i think you are referring partition scheme to a type/subtype but not the partition label. however, the constant that was in the LITTLEFS, i believe was the partition label which suppose to be a subType. correct me if i am wrong. but i did some changes to the constant to select different partition to be able to load the partition and read the content as below.

`	
#define FILESYSTEM LITTLEFS
#include <LITTLEFS.h>
`
`while (!FILESYSTEM.begin(false, "/folder", 10, partition_label)) {
	if (!mount_spiffs(false, partition_label)) {
		Serial.println("SPIFFS Mount Failed");
	}
}`

`FILESYSTEM.open('/');`

i did not have good knowledge on how the upload library work and havent try those to say. let me know if there is approach to load a partition before reading its content other then the one i use above.

**Comment by lorol** [comment]
Hi @tsctrl 

Please submit a PR with changes with what you believe is necessary. It is feasible the label to be used as a parameter.
However keep in mind:
- If you propose a name for the default value, different than "spiffs" then you should submit a PR to the core to include dedicated partition schemes for LittleFS with your default label name.
- Before next major esp32 core release, 2.x it will not be considered, I believe

The main purpose of all this library was to bring to Arduino the robustness of new filesystem as simple, straightforward possible for general usage.

Of course I will keep your suggestions in mind.
Please test, provide some sketches with usage of 2 x data partitions of same type etc.

Additionally,  I would like to show you **another thing** as you want to use non-defaults; here is about the other parameter - mounting point  :)
https://github.com/espressif/arduino-esp32/commit/882b12c44e9aca640a8adad16c11cd41c67e0f7b
Yes it is "ugly" but this is the reality to get tings working :+1: 

Thank you,
