### ISSUE TITLE
Need to call close while listing files in SPIFFS with openNextFile

### ISSUE THREAD

**Issue by console-netsphere** [lorol/LITTLEFS#23]
Hi,

I've been taking a look at the LITTLEFS example LittleFS_test.ino, in particular to the listDir function.

I've noticed that the procedure doesn't make any call to the close method. It just keeps calling the openNextFile method until there are no more files available.

Isn't a call to the close method needed to make sure no resources are left hanging?

Regards

**Comment by wesee-dev** [comment]
As far as I could understand a C++ smart pointer is responsible for closing the file when variable is overwritten or gets out of scope.

**Comment by console-netsphere** [comment]
As far as I could understand a C++ smart pointer is responsible for closing the file when variable is overwritten or gets out of scope.
