### ISSUE TITLE
Linking fails with ESP32-C3 latest Arduino git (IDF4.4 riscv32 toolchain)

### ISSUE THREAD

**Issue by Jason2866** [lorol/LITTLEFS#30]
Like LITTLEFS a lot. Works great with ESP32 :-)

Trying to build with the ESP32-C3 fails with linking error (using included LITTLEFS lib in Arduino): 
```
c:/users/hans/.platformio/packages/toolchain-riscv32/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld.exe: C:\Users\Hans\.platformio\packages\framework-arduinoespressif32@src-334b65656024015419a5766890f3216e\tools\sdk\esp32c3\lib\libesp_littlefs.a(esp_littlefs.c.obj): in function `esp_littlefs_init':
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/build/../components/esp_littlefs/src/esp_littlefs.c:492: undefined reference to `g_rom_flashchip'
c:/users/hans/.platformio/packages/toolchain-riscv32/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld.exe: /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/build/../components/esp_littlefs/src/esp_littlefs.c:492: undefined reference to `g_rom_flashchip'
```
THX!

**Comment by lorol** [comment]
Hi,
If you are using core V2 then remove this separate library from your sets. It is only to be used with Arduino esp32 core v1.x. that doesn't have it included. (one or the other way)
If you still have problems please direct your questions at plafromio, esp32 core v2 or joltwallet/esp_littlefs.
Now everything is built from IDF side
This place gets depreciated and I will disable posting the issues soon.
