### ISSUE TITLE
'Dir' was not declared in this scope

### ISSUE THREAD

**Issue by PQCraft** [lorol/LITTLEFS#8]
```
#include <Arduino.h>
#include <FS.h>
#include <LITTLEFS.h>
#include <esp_int_wdt.h>
#include <esp_task_wdt.h>
#include <esp32-hal-cpu.h>
#include <stdlib.h>
void setup() {
  Dir dir = fs.open("/");
}
```
The Arduino compiler throws `'Dir' was not declared in this scope`. Is there any other way I can list all the files in a directory?

**Comment by PQCraft** [comment]
`LITTLEFS::Dir dir = fs.open("/");` causes `'LITTLEFS' is not a class, namespace, or enumeration`
and
`fs::Dir dir = fs.open("/");` does the same

**Comment by lorol** [comment]
Use File, 
Check in the provided examples.
Also you can see here the difference with esp8266:
https://github.com/lorol/ESPAsyncWebServer/blob/master/src/SPIFFSEditor.cpp#L187

**Comment by PQCraft** [comment]
@lorol 
```
#include <Arduino.h>
#include <FS.h>
#include <LITTLEFS.h>
#include <esp_int_wdt.h>
#include <esp_task_wdt.h>
#include <esp32-hal-cpu.h>
#include <stdlib.h>
#define lfs LITTLEFS
void setup() {
  String tmpStr = "";
  File dir = lfs.open("/");
  while (dir.next()) {
    tmpStr += dir.fileName();
    tmpStr += " / ";
    tmpStr += dir.fileSize();
    tmpStr += "\r\n";
  }
  Serial.print(str);
}
```
`'class fs::File' has no member named 'next'`

**Comment by lorol** [comment]
Please use openNextFile(); 
Everything is shown in the link in previous message.

**Comment by PQCraft** [comment]
@lorol Ok thanks! It works now!
